"""The App's side of authentication, against a stub GitHub that answers its two endpoints.

No test reaches github.com. The private key is a real one generated by openssl, so the JWT
these tests inspect is verified the way GitHub would verify it.
"""

import base64
import json
import logging
import subprocess
import tempfile
import threading
import time
import unittest
from datetime import UTC, datetime, timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from control_panel.integrations import github_app

OWNER, REPOSITORY = "shaielc", "code-winch"
URL = f"https://github.com/{OWNER}/{REPOSITORY}"
APP_ID = "123456"
INSTALLATION = 4242


def unpad(segment: str) -> bytes:
    return base64.urlsafe_b64decode(segment + "=" * (-len(segment) % 4))


class FakeGitHub(BaseHTTPRequestHandler):
    """Answer `GET /repos/.../installation` and the installation token endpoint.

    `installation` set to None answers the lookup with 404, as GitHub does when the App is
    not installed; `refusals` answers that many token requests with a status before minting.
    """

    installation: int | None
    expiry: timedelta
    delay: float
    filler: str
    minted: list
    received: list
    refusals: list

    def log_message(self, *args):
        return

    def reply(self, status: int, body: dict):
        payload = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def record(self) -> None:
        self.received.append((self.command, self.path,
                              self.headers.get("Authorization", "").removeprefix("Bearer ")))

    def do_GET(self):
        self.record()
        if self.installation is None:
            self.reply(404, {"message": "Not Found"})
            return
        self.reply(200, {"id": self.installation, "app_slug": "code-winch-app",
                         "account": {"login": OWNER, "bio": self.filler}})

    def do_POST(self):
        self.record()
        if self.refusals:
            self.reply(self.refusals.pop(0), {"message": "Refused"})
            return
        time.sleep(self.delay)
        self.minted.append(f"ghs_installation{len(self.minted):08d}")
        expires = datetime.now(UTC) + self.expiry
        self.reply(201, {"token": self.minted[-1],
                         "expires_at": expires.isoformat(timespec="seconds").replace("+00:00", "Z")})


class GitHubAppFixture:
    @classmethod
    def setUpClass(cls):
        cls._keys = tempfile.TemporaryDirectory()
        keys = Path(cls._keys.name)
        cls.private_key = keys / "app.pem"
        cls.public_key = keys / "app.pub"
        subprocess.run(("openssl", "genpkey", "-quiet", "-algorithm", "RSA",
                        "-pkeyopt", "rsa_keygen_bits:2048", "-out", str(cls.private_key)),
                       check=True, capture_output=True)
        subprocess.run(("openssl", "rsa", "-in", str(cls.private_key), "-pubout",
                        "-out", str(cls.public_key)), check=True, capture_output=True)

    @classmethod
    def tearDownClass(cls):
        cls._keys.cleanup()

    def setUp(self):
        silence, panel = logging.NullHandler(), logging.getLogger("control_panel")
        panel.addHandler(silence)
        self.addCleanup(panel.removeHandler, silence)
        self.github = type("Handler", (FakeGitHub,), {
            "installation": INSTALLATION, "expiry": timedelta(hours=1), "delay": 0.0,
            "filler": "an account", "minted": [], "received": [], "refusals": [],
        })
        self.server = ThreadingHTTPServer(("127.0.0.1", 0), self.github)
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        self.addCleanup(self.server.server_close)
        self.addCleanup(self.server.shutdown)
        self.api = "http://%s:%d" % self.server.server_address

    def auth(self, url: str = URL) -> github_app.GitHubAppAuth:
        return github_app.GitHubAppAuth(APP_ID, self.private_key, url, api=self.api)

    def asked(self, method: str) -> list:
        return [call for call in self.github.received if call[0] == method]


class InstallationTests(GitHubAppFixture, unittest.TestCase):
    def test_the_installation_is_resolved_from_the_repository_url(self):
        self.assertEqual(self.auth().token(), self.github.minted[0])
        lookup, mint = self.github.received
        self.assertEqual(lookup[1], f"/repos/{OWNER}/{REPOSITORY}/installation")
        self.assertEqual(mint[1], f"/app/installations/{INSTALLATION}/access_tokens")

    def test_an_installation_longer_than_a_refusals_body_is_still_read_whole(self):
        # An installation carries its whole account object, so the reply is not small.
        self.github.filler = "x" * (github_app.BODY * 2)
        self.assertEqual(self.auth().token(), self.github.minted[0])

    def test_an_app_that_is_not_installed_names_the_repository_it_is_missing_from(self):
        self.github.installation = None
        with self.assertRaises(github_app.ConfigurationError) as error:
            self.auth().token()
        self.assertIn(f"{OWNER}/{REPOSITORY}", str(error.exception))
        self.assertIn("not installed", str(error.exception))
        self.assertEqual(self.github.minted, [])

    def test_rejected_app_credentials_name_what_to_check(self):
        self.github.refusals = [401]
        with self.assertRaises(github_app.ConfigurationError) as error:
            self.auth().token()
        self.assertIn("GITHUB_APP_ID", str(error.exception))
        # A rejected key is not a missing installation, so it is not looked up again.
        self.assertEqual(len(self.asked("GET")), 1)

    def test_a_reinstalled_app_is_resolved_again_rather_than_wedging(self):
        self.github.refusals = [404]
        auth = self.auth()
        self.assertEqual(auth.token(), self.github.minted[0])
        self.assertEqual(len(self.asked("GET")), 2)
        self.assertEqual(len(self.asked("POST")), 2)

    def test_a_url_that_names_no_repository_is_refused_before_any_request(self):
        for url in ("https://github.com/shaielc", "https://github.com/a/b/c",
                    "git@github.com:shaielc/code-winch.git", "", "https://github.com/"):
            with self.assertRaises(github_app.ConfigurationError):
                self.auth(url)
        self.assertEqual(self.github.received, [])

    def test_a_repository_url_is_read_the_way_git_accepts_it(self):
        for url in (URL, URL + ".git", URL + "/"):
            self.assertEqual(github_app.repository_path(url), (OWNER, REPOSITORY))
        self.assertEqual(github_app.host(URL), "github.com")
        self.assertEqual(github_app.api_base(URL), "https://api.github.com")
        self.assertEqual(github_app.api_base("https://git.example/o/r"),
                         "https://git.example/api/v3")


class TokenLifetimeTests(GitHubAppFixture, unittest.TestCase):
    def test_a_token_in_hand_is_reused_and_the_installation_resolved_once(self):
        auth = self.auth()
        self.assertEqual({auth.token() for _ in range(4)}, {self.github.minted[0]})
        self.assertEqual(len(self.github.minted), 1)
        self.assertEqual(len(self.asked("GET")), 1)

    def test_a_token_near_its_expiry_is_replaced(self):
        # Inside the refresh margin, so the token in hand is never good enough to reuse.
        self.github.expiry = github_app.MARGIN - timedelta(minutes=1)
        auth = self.auth()
        self.assertNotEqual(auth.token(), auth.token())
        self.assertEqual(len(self.github.minted), 2)
        # The installation is still only resolved once; it is the token that expires.
        self.assertEqual(len(self.asked("GET")), 1)

    def test_a_reply_without_a_readable_expiry_is_held_briefly(self):
        auth = self.auth()
        for unreadable in (None, "not a date", 17):
            held = auth._expiry(unreadable) - github_app.now()
            self.assertLessEqual(held, github_app.UNKNOWN_EXPIRY)
            self.assertGreater(held, github_app.UNKNOWN_EXPIRY - timedelta(seconds=5))
        # GitHub's own expiry carries a zone, and one without is still not local time.
        self.assertEqual(auth._expiry("2026-10-07T12:00:00Z"),
                         auth._expiry("2026-10-07T12:00:00"))

    def test_simultaneous_callers_share_one_mint(self):
        self.github.delay = 0.2
        auth = self.auth()
        answers, threads = [], [None] * 5
        for index in range(len(threads)):
            threads[index] = threading.Thread(target=lambda: answers.append(auth.token()))
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join(10)
        self.assertEqual(len(answers), len(threads))
        self.assertEqual(set(answers), {self.github.minted[0]})
        self.assertEqual(len(self.github.minted), 1)


class AppJwtTests(GitHubAppFixture, unittest.TestCase):
    def claims(self) -> tuple[dict, dict, str]:
        self.auth().token()
        jwt = self.github.received[0][2]
        header, claims, _ = jwt.split(".")
        return json.loads(unpad(header)), json.loads(unpad(claims)), jwt

    def test_the_jwt_claims_the_app_for_under_ten_minutes(self):
        header, claims, _ = self.claims()
        self.assertEqual(header, {"alg": "RS256", "typ": "JWT"})
        self.assertEqual(claims["iss"], APP_ID)
        self.assertLessEqual(claims["exp"] - claims["iat"], 600)
        # Backdated, because GitHub refuses a JWT issued in its future.
        self.assertLess(claims["iat"], time.time())

    def test_the_jwt_signature_verifies_against_the_apps_public_key(self):
        _, _, jwt = self.claims()
        signing_input, _, signature = jwt.rpartition(".")
        with tempfile.TemporaryDirectory() as scratch:
            signed = Path(scratch) / "signature"
            signed.write_bytes(unpad(signature))
            verify = subprocess.run(
                ("openssl", "dgst", "-sha256", "-verify", str(self.public_key),
                 "-signature", str(signed)),
                input=signing_input.encode(), capture_output=True)
        self.assertEqual(verify.returncode, 0, verify.stderr)

    def test_the_pkcs1_key_github_hands_out_signs_too(self):
        traditional = self.private_key.parent / "traditional.pem"
        subprocess.run(("openssl", "rsa", "-in", str(self.private_key), "-traditional",
                        "-out", str(traditional)), check=True, capture_output=True)
        self.assertIn("BEGIN RSA PRIVATE KEY", traditional.read_text())
        auth = github_app.GitHubAppAuth(APP_ID, traditional, URL, api=self.api)
        self.assertEqual(auth.token(), self.github.minted[0])

    def test_a_key_that_cannot_sign_is_a_configuration_error_naming_no_key(self):
        broken = self.private_key.parent / "broken.pem"
        broken.write_text("-----BEGIN PRIVATE KEY-----\nnot-a-key\n-----END PRIVATE KEY-----\n")
        auth = github_app.GitHubAppAuth(APP_ID, broken, URL, api=self.api)
        with self.assertRaises(github_app.ConfigurationError) as error:
            auth.token()
        self.assertIn("GITHUB_APP_PRIVATE_KEY_FILE", str(error.exception))
        self.assertNotIn("not-a-key", str(error.exception))
        self.assertEqual(self.github.received, [])

    def test_a_missing_key_file_is_refused_at_startup(self):
        for key in (self.private_key.parent / "absent.pem", self.private_key.parent):
            with self.assertRaises(github_app.ConfigurationError) as error:
                github_app.GitHubAppAuth(APP_ID, key, URL, api=self.api)
            self.assertIn("GITHUB_APP_PRIVATE_KEY_FILE", str(error.exception))
        with self.assertRaises(github_app.ConfigurationError) as error:
            github_app.GitHubAppAuth("", self.private_key, URL, api=self.api)
        self.assertIn("GITHUB_APP_ID", str(error.exception))
