// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"time"
)

// Defines values for EventSensitivity.
const (
	Confidential EventSensitivity = "confidential"
	Operational  EventSensitivity = "operational"
	Public       EventSensitivity = "public"
	Secret       EventSensitivity = "secret"
	UserContent  EventSensitivity = "user-content"
)

// Event defines model for Event.
type Event struct {
	EventId       string                  `json:"eventId"`
	Extensions    *map[string]interface{} `json:"extensions,omitempty"`
	Kind          string                  `json:"kind"`
	OccurredAt    time.Time               `json:"occurredAt"`
	Payload       map[string]interface{}  `json:"payload"`
	RunId         RunId                   `json:"runId"`
	SchemaVersion int                     `json:"schemaVersion"`
	Sensitivity   EventSensitivity        `json:"sensitivity"`
	Sequence      int64                   `json:"sequence"`
	Source        map[string]interface{}  `json:"source"`
}

// EventSensitivity defines model for Event.Sensitivity.
type EventSensitivity string

// EventPage defines model for EventPage.
type EventPage struct {
	Events            []Event `json:"events"`
	HasMore           bool    `json:"hasMore"`
	NextAfterSequence int64   `json:"nextAfterSequence"`
}
