// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"time"
)

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	HarnessProfile string `json:"harnessProfile"`
	SandboxProfile string `json:"sandboxProfile"`

	// WorkspacePath Workspace reference; it must not contain credentials.
	WorkspacePath string `json:"workspacePath"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt      time.Time `json:"createdAt"`
	HarnessProfile string    `json:"harnessProfile"`
	Id             RunId     `json:"id"`
	LastSequence   *int64    `json:"lastSequence,omitempty"`
	SandboxProfile string    `json:"sandboxProfile"`
	State          RunState  `json:"state"`
	UpdatedAt      time.Time `json:"updatedAt"`

	// Version Monotonic concurrency version represented by ETag.
	Version       int64  `json:"version"`
	WorkspacePath string `json:"workspacePath"`
}

// StopRunRequest defines model for StopRunRequest.
type StopRunRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// RunAccepted defines model for RunAccepted.
type RunAccepted = Run
