// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

// Defines values for InputAcceptedKind.
const (
	InputAcceptedKindInterrupt     InputAcceptedKind = "interrupt"
	InputAcceptedKindResize        InputAcceptedKind = "resize"
	InputAcceptedKindTerminalBytes InputAcceptedKind = "terminal_bytes"
	InputAcceptedKindText          InputAcceptedKind = "text"
)

// Defines values for RunInputRequestKind.
const (
	RunInputRequestKindInterrupt     RunInputRequestKind = "interrupt"
	RunInputRequestKindResize        RunInputRequestKind = "resize"
	RunInputRequestKindTerminalBytes RunInputRequestKind = "terminal_bytes"
	RunInputRequestKindText          RunInputRequestKind = "text"
)

// InputAccepted defines model for InputAccepted.
type InputAccepted struct {
	Accepted  bool              `json:"accepted"`
	CommandId string            `json:"commandId"`
	Kind      InputAcceptedKind `json:"kind"`
	RunId     RunId             `json:"runId"`
}

// InputAcceptedKind defines model for InputAccepted.Kind.
type InputAcceptedKind string

// RunInputRequest defines model for RunInputRequest.
type RunInputRequest struct {
	Bytes   *[]byte             `json:"bytes,omitempty"`
	Columns *int                `json:"columns,omitempty"`
	Kind    RunInputRequestKind `json:"kind"`
	Rows    *int                `json:"rows,omitempty"`
	Text    *string             `json:"text,omitempty"`
}

// RunInputRequestKind defines model for RunInputRequest.Kind.
type RunInputRequestKind string
