// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EventSensitivity.
const (
	Confidential EventSensitivity = "confidential"
	Operational  EventSensitivity = "operational"
	Public       EventSensitivity = "public"
	Secret       EventSensitivity = "secret"
	UserContent  EventSensitivity = "user-content"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for InputAcceptedKind.
const (
	InputAcceptedKindInterrupt     InputAcceptedKind = "interrupt"
	InputAcceptedKindResize        InputAcceptedKind = "resize"
	InputAcceptedKindTerminalBytes InputAcceptedKind = "terminal_bytes"
	InputAcceptedKindText          InputAcceptedKind = "text"
)

// Defines values for RunInputRequestKind.
const (
	RunInputRequestKindInterrupt     RunInputRequestKind = "interrupt"
	RunInputRequestKindResize        RunInputRequestKind = "resize"
	RunInputRequestKindTerminalBytes RunInputRequestKind = "terminal_bytes"
	RunInputRequestKindText          RunInputRequestKind = "text"
)

// Defines values for RunState.
const (
	Cancelled RunState = "cancelled"
	Completed RunState = "completed"
	Created   RunState = "created"
	Failed    RunState = "failed"
	Preparing RunState = "preparing"
	Queued    RunState = "queued"
	Running   RunState = "running"
	Stopping  RunState = "stopping"
)

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	HarnessProfile string `json:"harnessProfile"`
	SandboxProfile string `json:"sandboxProfile"`

	// WorkspacePath Workspace reference; it must not contain credentials.
	WorkspacePath string `json:"workspacePath"`
}

// Event defines model for Event.
type Event struct {
	EventId       string                  `json:"eventId"`
	Extensions    *map[string]interface{} `json:"extensions,omitempty"`
	Kind          string                  `json:"kind"`
	OccurredAt    time.Time               `json:"occurredAt"`
	Payload       map[string]interface{}  `json:"payload"`
	RunId         RunId                   `json:"runId"`
	SchemaVersion int                     `json:"schemaVersion"`
	Sensitivity   EventSensitivity        `json:"sensitivity"`
	Sequence      int64                   `json:"sequence"`
	Source        map[string]interface{}  `json:"source"`
}

// EventSensitivity defines model for Event.Sensitivity.
type EventSensitivity string

// EventPage defines model for EventPage.
type EventPage struct {
	Events            []Event `json:"events"`
	HasMore           bool    `json:"hasMore"`
	NextAfterSequence int64   `json:"nextAfterSequence"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// InputAccepted defines model for InputAccepted.
type InputAccepted struct {
	Accepted  bool              `json:"accepted"`
	CommandId string            `json:"commandId"`
	Kind      InputAcceptedKind `json:"kind"`
	RunId     RunId             `json:"runId"`
}

// InputAcceptedKind defines model for InputAccepted.Kind.
type InputAcceptedKind string

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail Actionable summary that contains no content or secrets.
	Detail string        `json:"detail"`
	Errors *[]FieldError `json:"errors,omitempty"`

	// RequestId Correlation identifier safe to include in logs.
	RequestId string `json:"requestId"`
	Status    int    `json:"status"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt      time.Time `json:"createdAt"`
	HarnessProfile string    `json:"harnessProfile"`
	Id             RunId     `json:"id"`
	LastSequence   *int64    `json:"lastSequence,omitempty"`
	SandboxProfile string    `json:"sandboxProfile"`
	State          RunState  `json:"state"`
	UpdatedAt      time.Time `json:"updatedAt"`

	// Version Monotonic concurrency version represented by ETag.
	Version       int64  `json:"version"`
	WorkspacePath string `json:"workspacePath"`
}

// RunId defines model for RunId.
type RunId = string

// RunInputRequest defines model for RunInputRequest.
type RunInputRequest struct {
	Bytes   *[]byte             `json:"bytes,omitempty"`
	Columns *int                `json:"columns,omitempty"`
	Kind    RunInputRequestKind `json:"kind"`
	Rows    *int                `json:"rows,omitempty"`
	Text    *string             `json:"text,omitempty"`
}

// RunInputRequestKind defines model for RunInputRequest.Kind.
type RunInputRequestKind string

// RunState defines model for RunState.
type RunState string

// StopRunRequest defines model for StopRunRequest.
type StopRunRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// ProblemBadRequest defines model for ProblemBadRequest.
type ProblemBadRequest = Problem

// ProblemIdempotencyConflict defines model for ProblemIdempotencyConflict.
type ProblemIdempotencyConflict = Problem

// ProblemPreconditionFailed defines model for ProblemPreconditionFailed.
type ProblemPreconditionFailed = Problem

// ProblemPreconditionRequired defines model for ProblemPreconditionRequired.
type ProblemPreconditionRequired = Problem

// ProblemRunNotFound defines model for ProblemRunNotFound.
type ProblemRunNotFound = Problem

// ProblemStateConflict defines model for ProblemStateConflict.
type ProblemStateConflict = Problem

// ProblemUnauthorized defines model for ProblemUnauthorized.
type ProblemUnauthorized = Problem

// ProblemUnsupportedProfile defines model for ProblemUnsupportedProfile.
type ProblemUnsupportedProfile = Problem

// ProblemValidationFailed defines model for ProblemValidationFailed.
type ProblemValidationFailed = Problem

// RunAccepted defines model for RunAccepted.
type RunAccepted = Run

// CreateRunParams defines parameters for CreateRun.
type CreateRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	// AfterSequence Return events with a sequence strictly greater than this value.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
	Limit         *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	// AfterSequence Resume strictly after this durable sequence.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
}

// SendRunInputParams defines parameters for SendRunInput.
type SendRunInputParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StartRunParams defines parameters for StartRun.
type StartRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StopRunParams defines parameters for StopRun.
type StopRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// SendRunInputJSONRequestBody defines body for SendRunInput for application/json ContentType.
type SendRunInputJSONRequestBody = RunInputRequest

// StopRunJSONRequestBody defines body for StopRun for application/json ContentType.
type StopRunJSONRequestBody = StopRunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Report service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create a run
	// (POST /runs)
	CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams)
	// Read a run
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// Read a page of durable run events
	// (GET /runs/{runId}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams)
	// Resume an ordered run event WebSocket stream
	// (GET /runs/{runId}/events/stream)
	StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams)
	// Send idempotent input to a running run
	// (POST /runs/{runId}/input)
	SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams)
	// Start a created run
	// (POST /runs/{runId}/start)
	StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams)
	// Stop a run
	// (POST /runs/{runId}/stop)
	StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Report service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a run
// (POST /runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a run
// (GET /runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a page of durable run events
// (GET /runs/{runId}/events)
func (_ Unimplemented) ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resume an ordered run event WebSocket stream
// (GET /runs/{runId}/events/stream)
func (_ Unimplemented) StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send idempotent input to a running run
// (POST /runs/{runId}/input)
func (_ Unimplemented) SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a created run
// (POST /runs/{runId}/start)
func (_ Unimplemented) StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop a run
// (POST /runs/{runId}/stop)
func (_ Unimplemented) StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamRunEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendRunInput operation middleware
func (siw *ServerInterfaceWrapper) SendRunInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SendRunInputParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendRunInput(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StartRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopRun operation middleware
func (siw *ServerInterfaceWrapper) StopRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs", wrapper.CreateRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events", wrapper.ListRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events/stream", wrapper.StreamRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/input", wrapper.SendRunInput)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/start", wrapper.StartRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/stop", wrapper.StopRun)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbXPbNvL/Khj8O/N/UerBjpOLda/cTHpNm7Qeu0lvarseiFxJqEmAxYNs1aP77DcL",
	"gCQo0bYkK+3dTf0iVkQC2N3fPvywgO9pKotSChBG09E9nQHLQLmPb39kU/ydgU4VLw2Xgo7ouVFSTMmc",
	"5TxjRiqioFSgQRgupsTMgCgr/l+T1CoFwpA5KM2l6NOE6nQGBcMpzaIEOqLaKC6mdLlM6LsMilIaEOni",
	"O1isLxs9JzewIExrmXJmICO33Mz8wqBLKTQ8vtYyoSVTrAAT9Hxq6Tc5B2F6UxCg3II3sOiTM7Aa/NqM",
	"ZHwyAaeugt8saPxtrBKaMEF4JHoqxSTnqUEROU7u7U0TKlgBbT17KE1CcUauIKMjoyzEmhXs7j2IqZnR",
	"0cHh64QWXNT/RyWNAYVr/HJx0vuZ9X4f9o771//qXX35BU26IJh8YCadPQg5+gOZKFk4YxfSaZmCMPmC",
	"KGAZAt94AzMB9W41Jz2/2GP6RRpc0otfLunl5eWlwn/E1ZeXtFuLMyveZTjarVsyM2tWVe7ZY0t+oWBC",
	"R/T/Bk1UDPxTPfAzOweqPM35z6mS4xyKr1h25sHHL1MpDAj3kZVlzlNnj0Hp3/3yV42Wvadwx4oyBz8i",
	"QxnHLLsOTkQTmoFhPKcj+qPzb+9bY5ktCNdESOPjkHx7/sP3/aAYaIMGoMOD74Zv/3ny4fT922HrB6PD",
	"MGM1HR0Nhwk13KAE9CuEsF45WHZmTKlHgwFK17vlIp31M5hXeujBmGW9atByU0sGi3lbtn0t1jOVNs+c",
	"lmMgJVMasj4uEoZHofImhNWzLB/F6XUVpzEEHzUQRgTckpUgJROpupLAbogcN4i868gcm0MT6dOrR+8L",
	"I76Sj2+ZJqWCOZdW5wtiNWQPm6XB8FRBKkXGceavGc8hexaEZTTd9cTPFyF4hlkqlCjCBLq7UQufxLlp",
	"ahZmup3AOzhswItVI7UsG2IXK9ILg/cFnbZoU8h8QheS5FJMISrkurLRQ0id1flzX1jVGTlC6xzlXHRQ",
	"Cic3F6QqIjtBhQWzE6pIlF3AqofvA65KQ8z21cQurMyMa5LKomCilRPPrPhemq+lFc8DR1lxLaS5nriZ",
	"uusQ+IqPkY852r26W8o7aqA4s6KZbXMIlBU9IU3PD9tbIbKCZBK8fnDHtSFS1ZWXaz7OgRjpXDRleQ4q",
	"xuLcMAN7qUyIBloLOutSJWnKRKiV2jCF8DiyFic2N8mzyxJi5GbaoSghUG7s/ktS45ZGMaF9NHNNuPAk",
	"yccN1MZQlRoxaB8Fs2YmFf/9menNxhNFaH1ysuAz3DL56eLw3g2dgwadj+2FN8SlJe4+EDl5UEMXQx6T",
	"tuWxMEl03FMlJ7yy5s72r6e7LsN8raDhmmRQ5nJRoDOE4EGfaArOjCkBWjuqoJnIxvKOhLlIybjarfAc",
	"xljVQpJGyI0hqwf3qsF7zHwb6F+lwkaJ8cKXpsayMcSffNNgP1xvXk/WwfTeSKUgNQ7LOv455JlueB+i",
	"B0pJpenoosm1Tfl3A+iI3kp1o0uWwqnfTRagNZvC6pPYx+ny6pmu0dhqa/LYWGaf1PEHARi5hVTNDq0y",
	"qYJWRJ9ZcZKmUJpHIa6g3Xj3/ZCzBh7kmAgL66Komk3A9SbKnC18Zu1ob3UtGl4buHfa3ale6BE9Nmyl",
	"o7R0cgdFcOwbBczAmRVRw4BlnkCy/FTJEpThoOlownINCS2jr+5pCMsoSz7eCVppkiQ0xPLuE7QjYq1h",
	"9FP1mChwe78U/k64IYXVxiUM9AjGBUkVZFgkWK4RnUiKo+HxqyfEWMaNnIu1KF2x0prWV/WEcvwreB7y",
	"dl756eZoAI7xLac1O8GdAaG5FPrhSX0Lak2UG+4p/BNIyNTRmezEiT2RqmCGjmiGDMvwAmjHmJItcsmy",
	"rUVSVWttgy5Z5e+ffPs3aMILW8R6cGFgCsq9Do6yzblx4QUC37ygpR3nPKUJRemYF5Um1GpQvSqvJJhh",
	"Jjx4EiINqQITIRy5PkacSKFlLS7MqyOaPCWhtMoP3MJqK05aOUtS9yJrgVpYBvxXrVgL0bZXA+mDTn3q",
	"Ctb2ju0+cQOFfgp4HztLF8Xv/IBD11708jCl2AIfz5j+IBVE8TKWMgcm8KGAO3MyMaDON8JpuI5Tl8E1",
	"7Zq5EaXLal9jaXuL9GBLs3ke0ZEMAp3oeFITivsncpyfIvFrNOO65P8GWG5mZ6FRvaUOFSNp4lDedITT",
	"inRhVJc070RpTcwJthCGRcPWPSYU/wcScJVFKzUM3Bl3JmFAKVu6jSuogguWX48XBrRj9Jr/Dp3ZY5sM",
	"uGKcRs4m9kOM1wp2Wa5iZLs54epBDhvnQAqWzriAngKWuS8cCyY4pt9VLypWvTrdSeqkwRm0LQqmkPyz",
	"urrj3oCEHO3omMvKunOJiodvmGui4FyuZ5iId6+d5eG+IA9bUlcwJhw8UyRGEi7S3GZIZkkup92iNrFR",
	"sDufhl4eH0dJ6Wg47Cofgdh3OKn/IspzVnH6VLC5p9WstVR1agiYxcbo8i5k1Vt6luOuW/GNdb669grf",
	"nFfkTJu4OmQwYTY3rhhsVSm6eHAn2rCBbK7ZhwNsmW1rn3nDkdre+kEKaaTgKYaRb1uli+pEvenX+313",
	"dWixJatZo/KPux3PaGWURvAk8orYAsleSHl9olv3AOjw4Nth9w9tH3wPe8cnvW++/e7D96e9Hz/1fr66",
	"P3y1/KILBFwFi9RuWzJfO2LE8Zv2lub13168PupYOZW5LUQ7o7x6+fLFy6eg23dxk7c7COEWbe8gcdyr",
	"p/KXE/4BuM+roKs0C+5FE/qbBes+lApK5mZ29VT4T9rIsvQfMU5z8KPqDkrKRAp53qq1jQXOjSx33pUr",
	"YKGhEZniZVQLIkOsbxI0pFZxszjHlBJ8CpgCdWJ9WLpc47iP+7rdDfKdES4msqvkCaNYalz/u2CCTbmY",
	"EmVF1QpjWbi5wxXJrPKMAGkzmXFtpHKXXXy/h4nsUlSXH8hYZhw0ETAHVW/pFWiZzyGL9/a+GeP7h3AH",
	"qXX1d8ZEloPuXwratL3eyAzIT1ykM3Jy+i7KMSN60B/2h27PW4JgJacj+qI/7L/wIT9zNhvMHO3Fj1Nw",
	"CNb7RteG+wcYT4zpyiWOw+Fwb62qFer90DEsqDlPgXBNvNCLfssT6OjiKqGBWLnD61IqUw8LiuKIAYLp",
	"LsxI3aFz3W2i7ZtPF91aNK+s9bGanuZXMlvszV5r7bBlO1ngxnq5htfBH9FarA44QwL681qICX0vvXId",
	"Ec4EkgSWk49n74mc+FMuL7E/xn/0PtwyoUfe+7sEqq0+WL/n5EYebDzy48oZ09HweOOxXZd9cIrDw42n",
	"WDt9cNFWx5f3QsLQYk1YDe7dZm35WEbxofXZ0skD7vkmOsZcv3W3k5cunw3o0cZj45sKbSDcLZ0Aw7YZ",
	"K+wSrlbhGzTNrE4U33ONML6tukUrq7Ytf+budvoaqasroFUfj2BgpSZfkKlzKIV7YuFPxeYst1DfifzN",
	"glo0lxPZxIC6jtqBjXfsvMVZJveda+W84KZ7iZfDpGGAroH3GP/zJeEzOX7TuOxwfw8VkSoD5TdATKcg",
	"HJepjNinf2Ju22MolGwKmNcrdoYhHxx63xEy0EYBK6JAaZv9YzlVLANNjCQ/wfhcpjdgiPNd4pNJaPVY",
	"Bb1UyhsOq5cdHImEO6SkPyg+5YI0B5Z98sH3NP2hopMpISmz05m5tmWCaygzBmYSXIc5NmoLZ5WM61QK",
	"AakhKVNqgZ4QNwv65CRAFF1JmCjQM8guxe2M5+Arp5/Eb7EL18hCxul5ajttnDtjbZE4tC2iDOHN5g/M",
	"A7SN6/6BWWI1iA+8468c6tVol0oamcqc6Fvurt/9iVH2Yl1Q5G2NsMHFwk0FlufyNlwj3leIOkyZqFNR",
	"HZ2RFCGq9hetXJTW+Evyu8yXPLBXOAeRVZ2QZ28XkqdHhD85+Fw7i9WmzkYbi8O9Ld8+9ei634kvuA2G",
	"j//F4/cX/vuq2XYkv31jEgcfbE7vO66Suw3C651mqK84t6Md46O5+26IC0OshY6vitBZWd8+DNyVzM8Q",
	"rzjtPrb228bqesQ8buL4StBfbryDGx9uofXaRcrPEAjoeITFbYZOr5flPpx+lUZhQvRNS+7ImY+IJJzf",
	"4RP/tydV+xvFS5ADYErtd9A41/f9Hyh4Kx3s5fpfq/0VrRt2lv7jSo+RZd2daveJ22cFF1foXRrUvHJj",
	"q3I6ogNW8sH8ANnkvwMAAP//3t+qtvY7AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
