// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RunState.
const (
	Cancelled RunState = "cancelled"
	Completed RunState = "completed"
	Created   RunState = "created"
	Failed    RunState = "failed"
	Preparing RunState = "preparing"
	Queued    RunState = "queued"
	Running   RunState = "running"
	Stopping  RunState = "stopping"
)

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail Actionable summary that contains no content or secrets.
	Detail string        `json:"detail"`
	Errors *[]FieldError `json:"errors,omitempty"`

	// RequestId Correlation identifier safe to include in logs.
	RequestId string `json:"requestId"`
	Status    int    `json:"status"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

// RunId defines model for RunId.
type RunId = string

// RunState defines model for RunState.
type RunState string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// ProblemBadRequest defines model for ProblemBadRequest.
type ProblemBadRequest = Problem

// ProblemIdempotencyConflict defines model for ProblemIdempotencyConflict.
type ProblemIdempotencyConflict = Problem

// ProblemPreconditionFailed defines model for ProblemPreconditionFailed.
type ProblemPreconditionFailed = Problem

// ProblemPreconditionRequired defines model for ProblemPreconditionRequired.
type ProblemPreconditionRequired = Problem

// ProblemRunNotFound defines model for ProblemRunNotFound.
type ProblemRunNotFound = Problem

// ProblemStateConflict defines model for ProblemStateConflict.
type ProblemStateConflict = Problem

// ProblemUnauthorized defines model for ProblemUnauthorized.
type ProblemUnauthorized = Problem

// ProblemValidationFailed defines model for ProblemValidationFailed.
type ProblemValidationFailed = Problem

// RunAccepted defines model for RunAccepted.
type RunAccepted = Run

// CreateRunParams defines parameters for CreateRun.
type CreateRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	// AfterSequence Return events with a sequence strictly greater than this value.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
	Limit         *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	// AfterSequence Resume strictly after this durable sequence.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
}

// SendRunInputParams defines parameters for SendRunInput.
type SendRunInputParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StartRunParams defines parameters for StartRun.
type StartRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StopRunParams defines parameters for StopRun.
type StopRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// SendRunInputJSONRequestBody defines body for SendRunInput for application/json ContentType.
type SendRunInputJSONRequestBody = RunInputRequest

// StopRunJSONRequestBody defines body for StopRun for application/json ContentType.
type StopRunJSONRequestBody = StopRunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Report service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create a run
	// (POST /runs)
	CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams)
	// Read a run
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// Read a page of durable run events
	// (GET /runs/{runId}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams)
	// Resume an ordered run event WebSocket stream
	// (GET /runs/{runId}/events/stream)
	StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams)
	// Send idempotent input to a running run
	// (POST /runs/{runId}/input)
	SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams)
	// Start a created run
	// (POST /runs/{runId}/start)
	StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams)
	// Stop a run
	// (POST /runs/{runId}/stop)
	StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Report service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a run
// (POST /runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a run
// (GET /runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a page of durable run events
// (GET /runs/{runId}/events)
func (_ Unimplemented) ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resume an ordered run event WebSocket stream
// (GET /runs/{runId}/events/stream)
func (_ Unimplemented) StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send idempotent input to a running run
// (POST /runs/{runId}/input)
func (_ Unimplemented) SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a created run
// (POST /runs/{runId}/start)
func (_ Unimplemented) StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop a run
// (POST /runs/{runId}/stop)
func (_ Unimplemented) StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamRunEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendRunInput operation middleware
func (siw *ServerInterfaceWrapper) SendRunInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SendRunInputParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendRunInput(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StartRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopRun operation middleware
func (siw *ServerInterfaceWrapper) StopRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs", wrapper.CreateRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events", wrapper.ListRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events/stream", wrapper.StreamRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/input", wrapper.SendRunInput)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/start", wrapper.StartRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/stop", wrapper.StopRun)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba3PbNtb+Kxi8nXk/lLrYcbKx9pObSbduk9YjN+lObVcDkUcSahJgcZGterS/fecA",
	"vIASLUuykuzuNB9iWhSAg/M85wr4gcYyy6UAYTQdPNAZsASUe3z7M5vizwR0rHhuuBR0QC+NkmJK5izl",
	"CTNSEQW5Ag3CcDElZgZEWfH/msRWKRCGzEFpLkWXRlTHM8gYTmkWOdAB1UZxMaXLZUTPE8hyaUDEix9g",
	"sb5s8J7cwoIwrWXMmYGE3HEz8wuDzqXQsHmtZURzplgGptjnU0u/STkI05mCAOUWvIVFlwzBavBrM5Lw",
	"yQTcdhX8YUHjT2OV0IQJwgPRYykmKY8Nishxcq9vGlHBMmjus4PSRBRn5AoSOjDKQrizjN2/AzE1Mzo4",
	"On4d0YyL6nfcpDGgcI3frs46v7LOn/3OaXf0r87N11/RqA2CyXtm4tmjkCMfyETJzCk7k26XMQiTLogC",
	"liDwNRuYKVBv3+ak4xfbtL9gB9f06rdren19fa3wP3Hz9TVt38XQivMER7t1c2Zm9arKvdu05FcKJnRA",
	"/69XW0XPv9U9P7MjUMk0x58LJccpZN+wZOjBxw9jKQwI98jyPOWx00cv99/9+neNmn2gcM+yPAU/IkEZ",
	"xywZFSSiEU3AMJ7SAf3Z8dtzayyTBeGaCGm8HZLvL3/6sVtsDLRBBdD+0Q/9t/88e3/x7m2/8Q+twzBj",
	"NR2c9PsRNdygBPQbhLBaudDszJhcD3o9lK5zx0U86yYwL/ehe2OWdMpBy201WWjM67LJtXCfsbRp4nY5",
	"BpIzpSHp4iLF8MBU3hRm9SzNB3Y6Ku00hOCDBsKIgDuyYqRkIlWbE9gPkdMakfMWz7E9NMF+OtXoQ2HE",
	"V/zxHdMkVzDn0up0QayG5HG11BheKIilSDjO/C3jKSTPgjAPphtN/HwBgkP0UkWIIkwg3Y1aeCfOTR2z",
	"0NPtBd7RcQ1euDVSybIlduFGOsXgQ0GnLeoUEu/QhSSpFFMIArkudfQYUsPKfx4Kq8ojB2hdopyLlpTC",
	"yc0FKYPIXlBhwGyFKhBlH7Cq4YeAq9whevtyYmdWZsY1iWWWMdHwiUMrfpTmW2nF88BRVoyENKOJm6k9",
	"DoGP+Gj56KPdV/dzeSc1FEMr6tm2h0BZ0RHSdPywgwUiK0giwe8P7rk2RKoq8nLNxykQIx1FY5amoEIs",
	"Lg0zcJDIhGigtqA1LpWSxkwUsVIbphAel6yFjs1N8uywhBi5mfYISgiUG3v4kFTT0igmtLdmrgkXPkny",
	"dgOVMlS5jRC0D4JZM5OK//lM92bDiQK0PjpZ8B2WTH660Lz3Q+eoRudDc+EtcWmIewhEzh7dobMhj0mo",
	"+Y++ojxMIjCvJmtJA95IpSA2jgwVOTikia6TAoQBlJJYIl7VhljHBjeADuidVLc6ZzFc+FIjA63ZFFbf",
	"hAqgy5t9AlaQW9S62jmzqDVzyLziJwEIayZVnb6XKlXQgHtoxVkcQ242QlxCu51k9Ucj9JVDKx5zEkXM",
	"dFGLFWKg5JpNwNWxecoW3gpbWiFtMhRf67nvNDsZnaKfsGnYSvdh6eQu9oVjv0UtvkUmOhUlPs1g6YWS",
	"OSjDsQadsFRDRPPgo5Kya/2PirktbyrutnVo6qL5qpgi8mvU424qFsrx7+Bde0ma/YRfbUQwjLgZi2dc",
	"QEcBS9wHzlAJjumu9wRqw1+d7ix20uAM2mYZU5hsMqw7hWFcYJgnBT0dRSBWYHTrEqWreKDcQKaf4msA",
	"6rKajSnFFnTZcA1rvSh0XWnhUhP0rxMOnr2YiHARpzZBeyOpnLaLWjoU1z/imc3o4OXpqese+d98U8AP",
	"48LAFLyU3ve00MZ/8EAnUmXMYOxTvLU3E1LIvS1nraSqKFVgFiqjjV1Vt6cKAbR/9H2//R9tNsX6ndOz",
	"znff//D+x4vOzx87v948HL9aftWmsqEVLplzCwnU0RWNFTDjHO8fFqx7yBXkzI2JMGUT/kkbmef+EZmQ",
	"gh9V+e2YiRhSfL5pWTrwbDAHYUZv56W33N6a3MjzdpuHewNCcyn045P6Ltma8m+5rzKafce1FWTsMq7k",
	"zDRIkmASaHgGbRrP2SKVLNlZJFXyYYtGXulmP/oOdbETbwNHbRagwWWVc24WIRNyO055TCOK0jEvKo2o",
	"1aA6ZXRDIMXEW6x7651JK+QaGS/ipklxYV6d0OgpCaVVfuAOWlsxzJIsUdUurQRqYFngv6rFSoimvmpI",
	"28y4neUXRSzalenb++FHrAtDIbs/9zMcB+6wctEzpt9LFbrDsZQpMIEvBdybs4kBdbkVki3etg0SdI7r",
	"M9eiPKHXGbDUzEbfuR/Don+9o3br0FFyX962UHhF+mLUE/JhYchFbs3oHP8PU8QdJGTBsHVgiuTvEU9Y",
	"urNybwbujTu/MKCUzV2RCyrjgqWj8cKAdtFJ8z+h1Yx3cUUrGqvlrI2wMLZqg1urE5fAh+BwYgeF+o2G",
	"/MVPaBQePr3+24vXJ62xK7WZaKYar16+fPHyKTd2aCTk3R5CuEWbp2w47tVTdHfCP43O6I1LIIZW7AfM",
	"jCkBWl8oOeE+L9t8HLgeZphIxvJ+/wmale9aqvpL+ZoocAcAMfydcEMyq41roBVpNokVFHHRJayBFCf9",
	"01dPiLGi/NVqfEVLa7veAicsJncsXnxquEu+s47m2lf49nlNyrQJY08CE2ZT40LNTnGojSWtBQVsIZtP",
	"oZcRtXmyq37mdY7WZNl7KaSRgsdIJ9/ZixflpYP6SAMSMl5U5zo7ZlVrRN/MQZ7QUim14FHAilAD0aeg",
	"7KWR+d6ORQErei+BJb4MkqBg2+uZpIbYKm4Wl4h7EUKAKVBn1uvOEcLFZfdxs3HluzZcTGRb6SuMYrFx",
	"fdyMCTblYkqUFWXXjiXFDRSuSGKV7wxg5kRmXBup3KUN35piIrkW5SE+GcuEgyYC5qAqr6RAy3QOSeie",
	"fKPIoUHgHmLr6vAZE0kKunstaN2heyMTIL9wEc/I2cV5QIQBPer2u31XGOUgWM7pgL7o9rsvfHk6czrr",
	"+XQNH6fgEKyKC9cx/AcYn8nRlcsIx/3+p+iqtWePjx0wgprzGAjXxI9bdBvcoIOrm4gWLRd3LJtLZaph",
	"xdZxRA/hdVdBpG7RQhVCafNOz1X7vuqvrHXd6obsNzJZfKq+5FrIXzZ9B5ZnyzVAj75Am7Q82Cuc1pdr",
	"h0b0nfR7bfEITKDnZyn5MHxH5MSf7niJ/fH1xntgy4ieeGtpE6gCobd+v8eNPNp65IeVs5WT/unWY9su",
	"ueAUx8dbT7F2sOJssbI+T0rCUGO10fUeXOGx3OSBvOF9Dvezga1vgtO89ctne5F2+Wx8T7YeGx7YN3Fx",
	"l1UKVHZ1b0UmeLOKZq/uj7SC+o5rRPVt2W9YWbWp+aG74uhDrC5vQpa9IoJ2Fpt0QaaOX4qYGRP+3sKc",
	"pRaqq4F/WFCL+o4emxhQo6DlVJNl7zR2GT20rpXyjJv2JV72o7pedC2gTTmijx+f3g5Wm2Mt9uCxI1Il",
	"oHzWy3QMwuVGpVa79Av6vgPaRs6mgH6/zPbQBxQMP7TJ9LRRwLLAcppq/5BPFUtAEyPJLzC+lPEtGOLI",
	"TLx3KY6QrIJOLOUth9VLAC4phXtMcX9SfMoFqc9qu+S9P2Pz56lOpojEzE5nZmTzCNdQZgzMRLgOc9mt",
	"zZxWEq5jKQTEhsRMqQUyIawQu+SsgCg4qp8o0DNIrsXdjKfgI6ufxNdVmTsgwwzW571NP3LplLWDJ9E2",
	"C1yGV5vzFSW0NXU/o9tYteojT/yVPkeFdq6kkbFMib7j7lraF7SyF+uCYl5XC1tQrLjMxNJU3hXXaw9l",
	"og5TJipXVFlnIEVhVYezVtfz9JfH95kveqTSuASRlI3UZxcb0dMjiqv4n6cueaRRvFVxcvxpZWqeBbTd",
	"kMQvuFLFe4rF5lsd/31xb7dyoXnnEAcfbV8otFzGdqXG671mqC4JN/0CWlJ9e9wQhzNGTZfqiqKns16I",
	"9Nylxk9g2TjtIVoIu1r1uhltVnF4b+ovGn9xGiNtCAvbDa2clfkhKLuaLqE7881O7pIwz+eouP+Db/zf",
	"XpSnZChehLEeHWK3JV1z/eL/ucC22ghfrv/x1l+mt2XD6T/PAGVeNa2azeXmkcPVDZJNg5qXrLYqpQPa",
	"YznvzY8wifx3AAAA//9MrT/KBTsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
