// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EventSensitivity.
const (
	Confidential EventSensitivity = "confidential"
	Operational  EventSensitivity = "operational"
	Public       EventSensitivity = "public"
	Secret       EventSensitivity = "secret"
	UserContent  EventSensitivity = "user-content"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for InputAcceptedKind.
const (
	InputAcceptedKindInterrupt     InputAcceptedKind = "interrupt"
	InputAcceptedKindResize        InputAcceptedKind = "resize"
	InputAcceptedKindTerminalBytes InputAcceptedKind = "terminal_bytes"
	InputAcceptedKindText          InputAcceptedKind = "text"
)

// Defines values for RunInputRequestKind.
const (
	RunInputRequestKindInterrupt     RunInputRequestKind = "interrupt"
	RunInputRequestKindResize        RunInputRequestKind = "resize"
	RunInputRequestKindTerminalBytes RunInputRequestKind = "terminal_bytes"
	RunInputRequestKindText          RunInputRequestKind = "text"
)

// Defines values for RunState.
const (
	Cancelled RunState = "cancelled"
	Completed RunState = "completed"
	Created   RunState = "created"
	Failed    RunState = "failed"
	Preparing RunState = "preparing"
	Queued    RunState = "queued"
	Running   RunState = "running"
	Stopping  RunState = "stopping"
)

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	HarnessProfile string `json:"harnessProfile"`
	SandboxProfile string `json:"sandboxProfile"`

	// WorkspacePath Workspace reference; it must not contain credentials.
	WorkspacePath string `json:"workspacePath"`
}

// Event defines model for Event.
type Event struct {
	EventId       string                  `json:"eventId"`
	Extensions    *map[string]interface{} `json:"extensions,omitempty"`
	Kind          string                  `json:"kind"`
	OccurredAt    time.Time               `json:"occurredAt"`
	Payload       map[string]interface{}  `json:"payload"`
	RunId         RunId                   `json:"runId"`
	SchemaVersion int                     `json:"schemaVersion"`
	Sensitivity   EventSensitivity        `json:"sensitivity"`
	Sequence      int64                   `json:"sequence"`
	Source        map[string]interface{}  `json:"source"`
}

// EventSensitivity defines model for Event.Sensitivity.
type EventSensitivity string

// EventPage defines model for EventPage.
type EventPage struct {
	Events            []Event `json:"events"`
	HasMore           bool    `json:"hasMore"`
	NextAfterSequence int64   `json:"nextAfterSequence"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// InputAccepted defines model for InputAccepted.
type InputAccepted struct {
	Accepted  bool              `json:"accepted"`
	CommandId string            `json:"commandId"`
	Kind      InputAcceptedKind `json:"kind"`
	RunId     RunId             `json:"runId"`
}

// InputAcceptedKind defines model for InputAccepted.Kind.
type InputAcceptedKind string

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail Actionable summary that contains no content or secrets.
	Detail string        `json:"detail"`
	Errors *[]FieldError `json:"errors,omitempty"`

	// RequestId Correlation identifier safe to include in logs.
	RequestId string `json:"requestId"`
	Status    int    `json:"status"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt      time.Time `json:"createdAt"`
	HarnessProfile string    `json:"harnessProfile"`
	Id             RunId     `json:"id"`
	LastSequence   *int64    `json:"lastSequence,omitempty"`
	SandboxProfile string    `json:"sandboxProfile"`
	State          RunState  `json:"state"`
	UpdatedAt      time.Time `json:"updatedAt"`

	// Version Monotonic concurrency version represented by ETag.
	Version       int64  `json:"version"`
	WorkspacePath string `json:"workspacePath"`
}

// RunId defines model for RunId.
type RunId = string

// RunInputRequest defines model for RunInputRequest.
type RunInputRequest struct {
	Bytes   *[]byte             `json:"bytes,omitempty"`
	Columns *int                `json:"columns,omitempty"`
	Kind    RunInputRequestKind `json:"kind"`
	Rows    *int                `json:"rows,omitempty"`
	Text    *string             `json:"text,omitempty"`
}

// RunInputRequestKind defines model for RunInputRequest.Kind.
type RunInputRequestKind string

// RunState defines model for RunState.
type RunState string

// StopRunRequest defines model for StopRunRequest.
type StopRunRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// ProblemBadRequest defines model for ProblemBadRequest.
type ProblemBadRequest = Problem

// ProblemIdempotencyConflict defines model for ProblemIdempotencyConflict.
type ProblemIdempotencyConflict = Problem

// ProblemPreconditionFailed defines model for ProblemPreconditionFailed.
type ProblemPreconditionFailed = Problem

// ProblemPreconditionRequired defines model for ProblemPreconditionRequired.
type ProblemPreconditionRequired = Problem

// ProblemRunNotFound defines model for ProblemRunNotFound.
type ProblemRunNotFound = Problem

// ProblemStateConflict defines model for ProblemStateConflict.
type ProblemStateConflict = Problem

// ProblemUnauthorized defines model for ProblemUnauthorized.
type ProblemUnauthorized = Problem

// ProblemValidationFailed defines model for ProblemValidationFailed.
type ProblemValidationFailed = Problem

// RunAccepted defines model for RunAccepted.
type RunAccepted = Run

// CreateRunParams defines parameters for CreateRun.
type CreateRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	// AfterSequence Return events with a sequence strictly greater than this value.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
	Limit         *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	// AfterSequence Resume strictly after this durable sequence.
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
}

// SendRunInputParams defines parameters for SendRunInput.
type SendRunInputParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StartRunParams defines parameters for StartRun.
type StartRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// StopRunParams defines parameters for StopRun.
type StopRunParams struct {
	// IdempotencyKey Client-generated key. Reuse with a different request returns an idempotency conflict.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// IfMatch Strong ETag from the most recently read run representation.
	IfMatch IfMatch `json:"If-Match"`
}

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// SendRunInputJSONRequestBody defines body for SendRunInput for application/json ContentType.
type SendRunInputJSONRequestBody = RunInputRequest

// StopRunJSONRequestBody defines body for StopRun for application/json ContentType.
type StopRunJSONRequestBody = StopRunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Report service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Create a run
	// (POST /runs)
	CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams)
	// Read a run
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// Read a page of durable run events
	// (GET /runs/{runId}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams)
	// Resume an ordered run event WebSocket stream
	// (GET /runs/{runId}/events/stream)
	StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams)
	// Send idempotent input to a running run
	// (POST /runs/{runId}/input)
	SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams)
	// Start a created run
	// (POST /runs/{runId}/start)
	StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams)
	// Stop a run
	// (POST /runs/{runId}/stop)
	StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Report service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a run
// (POST /runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, params CreateRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a run
// (GET /runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a page of durable run events
// (GET /runs/{runId}/events)
func (_ Unimplemented) ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params ListRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resume an ordered run event WebSocket stream
// (GET /runs/{runId}/events/stream)
func (_ Unimplemented) StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send idempotent input to a running run
// (POST /runs/{runId}/input)
func (_ Unimplemented) SendRunInput(w http.ResponseWriter, r *http.Request, runId RunId, params SendRunInputParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a created run
// (POST /runs/{runId}/start)
func (_ Unimplemented) StartRun(w http.ResponseWriter, r *http.Request, runId RunId, params StartRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop a run
// (POST /runs/{runId}/stop)
func (_ Unimplemented) StopRun(w http.ResponseWriter, r *http.Request, runId RunId, params StopRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamRunEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamRunEventsParams

	// ------------- Optional query parameter "after_sequence" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_sequence", r.URL.Query(), &params.AfterSequence)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_sequence", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendRunInput operation middleware
func (siw *ServerInterfaceWrapper) SendRunInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SendRunInputParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendRunInput(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StartRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopRun operation middleware
func (siw *ServerInterfaceWrapper) StopRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopRunParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopRun(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs", wrapper.CreateRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events", wrapper.ListRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/events/stream", wrapper.StreamRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/input", wrapper.SendRunInput)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/start", wrapper.StartRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/stop", wrapper.StopRun)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW3Mbt5L+KyhsqvYhw4tk2WtxnxSXs3FiJyopdrYiKSoQ0yQRzQATXCgxKp7ffqqB",
	"uWDIkURSdHzOqejBojnTQHd/fQd0T7nKCyVBWkNH93QGLAXtP779mU3xdwqGa1FYoSQd0XOrlZySOctE",
	"yqzSREOhwYC0Qk6JnQHRTv63IdxpDdKSOWgjlOzThBo+g5zhknZRAB1RY7WQU7pcJvRdCnmhLEi++AEW",
	"69tGz8kNLAgzRnHBLKTkVthZ2BhMoaSBx/daJrRgmuVgSzmf2vpNJkDa3hQkaL/hDSz65AycgbA3I6mY",
	"TMCLq+EPBwZ/W6elIUwSEbHOlZxkgltkUeDiQd80oZLl0Jazh9wkFFcUGlI6stpBLFnO7t6DnNoZHR0c",
	"vk5oLmT9fxTSWtC4x28XJ71fWe/PYe+4f/2P3tXXX9GkC4LJB2b57EHI0R7IRKvcKztXXkoO0mYLooGl",
	"CHxjDcyWqHeLOemFzR6TL5Lgkl78dkkvLy8vNf4jr76+pN1SnDn5LkVqv2/B7KzZVftnj235lYYJHdH/",
	"GjReMQhPzSCs7A2osjRvP6dajTPIv2HpWQAfv+RKWpD+IyuKTHCvj0ER3v36d4Oavadwx/Iig0CRIo9j",
	"ll6XRkQTmoJlIqMj+rO372BbY5UuiDBEKhv8kHx//tOP/VIwMBYVQIcHPwzf/v/Jh9P3b4etH/QOy6wz",
	"dHQ0HCbUCosc0G8QwnrnUrMzawszGgyQu96tkHzWT2FeyWEGY5b2KqLlpposNRZ02ba1WE6uXJZ6KcdA",
	"CqYNpH3cpCSPXOVN6VbP0nzkp9eVn8YQfDRAGJFwS1aclEyU7goCuyFy3CDyriNybA5NJE+vpt4XRmIl",
	"Ht8yQwoNc6GcyRbEGUgfVkuD4akGrmQqcOVvmcggfRaERbTc9SSsFyF4hlGqTFGESTR3qxchiAvb5CyM",
	"dDuBd3DYgBeLRmpeNsQuFqRXEu8LOuNQp5CGgC4VyZScQpTITaWjh5A6q+PnvrCqI3KE1jnyuegoKTzf",
	"QpIqiewEFSbMTqgiVnYBqybfB1yVhBjtq4W9W9mZMISrPGeyFRPPnPxR2W+Vk88DRzt5LZW9nviVuvMQ",
	"hIyPno8x2r+6W8g7aqA4c7JZbXMItJM9qWwvkO0tETlJUgVBPrgTxhKl68wrjBhnQKzyJspZloGOsTi3",
	"zMJeMhOigdqCzrxUccqZLHOlsUwjPL5YiwObX+TZaQkx8ivtkJQQKE+7/5TUmKXVTJrgzcIQIUORFPwG",
	"amXoSowYtI+SOTtTWvz5zPDm4oUitD55XvAZtkxhudi9d0PnoEHnY3vjDXFpsbsPRE4elND7UMAk1vyn",
	"0FHupxCY14t1lAFvlNbArTeG2jgEZKlpigKEAbRW2CJeNI7Y5AZPQEf0VukbUzAOp6HVyMEYNoXVJ7EC",
	"6PJql4QV1RaNrrauLBrN7LOu+EkCwpor3ZTvlUo1tOA+c/KEcyjsoxBX0G7cmj0UFcok6dMUK/dFVg2b",
	"gG9ci4wtgtt1zD66Ni1fG/h32qOLXjlAeIxsZdyw9HyXgiDtGw3MwpmTUTfJ0lBdsOxUqwK0Fdh6Tlhm",
	"IKFF9NU9nTEtwZhTrSYiuMTjY4KVDjqhhsl0rO52X6DtEWvThF+qx0SDbww4/C8RluTOWJ9Y0SKYkIRr",
	"SDGCsMwgOhEXR8PjV0+wsYy7/Is1L13R0prUV/WCavw7hCT1dl7Z6eZoANKEecSanuDOgjRCSfPwomE+",
	"scbKjQj13RNIKO5zXXri2Z4onTNLRzTF9GtFDrSDpmCLTLF0a5Z0NXfZYIRS2funMBssJRG5y2M5hLQw",
	"Be1fB5/P58J69wKJb17Qwo0zwWlCkTsWWKUJdQZ0r4orCUaYiSgtCZEGrsFGCEemjx4nObS0JaR9dUST",
	"pzhUTgfCLbS2YqSVsST1oKpmqIVlif+qFmsm2vpqIH3QqE99wtresP0nYSE3TwEffGfpvfhdIDj0s6fA",
	"D9OaLfDxjJkPSkPkL2OlMmASH0q4sycTC/p8I5yG6zh1KdzQrpUbVrq09i2mtrdYHmyptlBHdASDspzo",
	"eFIXFPdPxLiwRBL2aOi6+P8OWGZnZ+UUc0sZqoqk8UN10+FOK9yVVF3cvJOFs3FNsAUzLCJbt5gy+T8Q",
	"gKsoWolh4c76gbUFrV3huxrQuZAsux4vLBhfmhvxJ3RGj20i4IpyGj4b3y99vBawS3NVRbabEa5O+Rm2",
	"sznjMyGhp4Gl/gtfBROk6Xfli6qqXl3uhHtucAXj8pzpBbEzVmd37KFJGaN9OeajsuncoqrDN4w1kXMu",
	"1yNMVHevHfRgX5CV/YpPGBMBoVLELl9InrkUi1mSqWk3q41v5OwuhKGXx8dRUDoaDrvSR1nYdxhp+CKK",
	"c04L+pSz+afVqjVXdWgoMYuV0WVdWFVvaVm+dt2q3livV9deEZvXFRkzNs4OKUyYy6xPBltliq46uBNt",
	"2IA3PwlCAlek2+pn3tRIbWv9oKSySgqObhRmGnxRHbc2w1xIyXhRT7S3rGrWSvnHzU6ktFJKw3gSWUWs",
	"gWQvRXl93FfPAOjw4Pth9w9tn4oOe8cnve++/+HDj6e9nz/1fr26P3y1/KoLBNwFk9RuLVnIHTHi+E27",
	"pXn9Py9eH3XszFXmctmOKK9evnzx8ino9p3c1O0OTPhN2x0k0r16Kn555h+A+7xyukqy0rxoQv9w4PyH",
	"QkPB/Mo+n8rwyVhVFOEj+mkGgaqeoHAmOWRZK9c2Gji3qti5K9fAyoFGpIqXUS6IFLHeJBjgTgu7OMeQ",
	"UtoUMA36xAW39LHG1z7+6/Y0KExGhJyorpQnrWbc+uFoziSbCjkl2slqFMbS8lqH0CR1OlQEWDaTmTBW",
	"aX8TIsx7mEwvZXUyTsYqFWCIhDnouqXXYFQ2hzTu7cMwxjs6gTvgzuffGZNpBqZ/KWkz9nqjUiC/CMln",
	"5OT0XRRjRvSgP+wPfc9bgGSFoCP6oj/svwguP/M6G8x82Ysfp+ARrPtGP4b7P7ChMKYrJ/yHw+HeRlUr",
	"pfdDZ3Sg54IDEYYEphf9liXQ0cVVQsvCyp9sFkrbmqwUFCkGCKa/TaFMh8z1tIm2r8VcdEvRvLI2x2pm",
	"mt+odLE3fa2Nw5btYIGN9XINr4O/YrRYnX6VAejLjRAT+l4F4To8nEksElhGPp69J2oSjkACx+GM99HL",
	"UsuEHgXr72Ko1vpg/RKMpzzYmPLjygHE0fB4Y9qumyC4xOHhxkusnT54b6v9K1ghYaixxq0G975ZWz4W",
	"UYJrfbZw8oB5vonOuNavZO1kpctnA3q0MW18jN0Gwl/hKGHYNmKVXcLVKnyDZpjVieJ7YRDGt9W0aGXX",
	"tubP/MW/kCNNdT+wmuMRdCxuswWZeoPS2BPLcJo/Z5mD+sLcHw70orm5xiYW9HU0DmysY+cWZ5ncd+6V",
	"iVzY7i1eDpOmAvQDvMfqv5ASPpPhN4PLDvMPUBGlU9ChAWKGg/S1TKXEPv2CsW2PrlCwKWBcr6ozdPnS",
	"oPftIQNjNbA8cpS22j8WU81SMMQq8guMzxW/AUu87ZIQTMpRj9PQ40rdCFg9CfdFJNxhSfqTFlMhSXNg",
	"2ScfwkwzHCp6nhLCmZvO7LUrEtxD2zEwm+A+zFejLvdaSYXhSkrglnCm9QItIR4W9MlJCVF0Xj3RYGaQ",
	"XsrbmcggZM6wSGixcz/Iwooz1KntsHHulbVF4DAujyJEUJsPDRW0jen+hVFi1YkPguGvHOrVaBdaWcVV",
	"Rsyt8HezvqCXvVhnFOu2htnSxMobPSzL1G15x3RfLuoxZbIORbV3RlyUXrU/bxWycDbcoN5lveSBXuEc",
	"ZFpNQp7dLiRPU5T30T9XZ7E61NmosTjc2/btU4+uy3/4gm8wgv8vHr+/8O+XzbYr8tvX6ZD4YPPyvuOe",
	"sW8QXu+0Qn3/te3t6B/NxWhLvBtiLvT1qiwnK+vtw8Df1/sM/orL7qO139ZX1z3mcRXHV4L+NuMvbsZo",
	"NoTFQ4JOm1XFPkx2tQjCcBZGjsKXVsGek/L0DZ+EPyuohtfIXoIZHANiv6MI81Pb/4B0tTJ/Xq7/IdLf",
	"vrbhXOhfz+NUUc+W2lPe9qT/4gqty4CeV2bsdEZHdMAKMZgfYC34zwAAAP//4ixLa9E5AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
